config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :likes, :except => [:new, :edit, :update]
  resources :ratings
  resources :comments
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'blockuser', to: 'users#change_blocked_status'
  root 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :password, length: { minimum: 5 },
                         format: { with: /([A-Z].*\d)|(\d.*[A-Z].*)/,message: "should contain one number and one capital letter" },
                         :on => [:create, :update]
#  Seuraava ei hyvaksy mitaan usernamea
#  validates :username, uniqueness: true,
#                         length: { minimum:3, maximum: 20 }
  validate do |user|
    user.errors[:username] << 'cannot be blank!' if user.username.nil?
    user.errors[:this_username] << 'is already in use!' if User.find_by(username: user.username)
    user.errors[:username_length] << 'has to be at least 3 letters!' if user.username && user.username.length < 3
    user.errors[:username_length] << 'cannot be more than 20 letters!' if user.username && user.username.length > 20
  end

  def to_s
    username
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change_blocked_status]
  before_action :ensure_that_signed_in, only: [:update, :destroy]
  before_action :ensure_that_not_blocked, only: [:create, :update, :destroy, :change_blocked_status]
  before_action :ensure_that_admin, only: [:change_blocked_status]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if @user == current_user || current_user.admin?
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_blocked_status
    if @user.blocked
      @user.update_attribute(:blocked, false)
    else 
      @user.update_attribute(:blocked, true)
    end
    redirect_to :back, notice: 'Blocked status changed!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<p style="color:#808080">Number of users: <%= @users.count %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <% if current_user && current_user.admin? %>
        <th>Admin</th>
        <th>Blocked</th>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <% if current_user && current_user.admin? %>
          <% if user.admin? %>
            <td><span class="label label-success">Admin account</span></td>
          <% else %>
            <td></td>
          <% end %>
          <% if user.blocked? %>
            <td><span class="label label-info">Account blocked</span></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.username %>
</p>

<ul>
  <% @user.posts.each do |post| %>
    <li>
      <h3><%= link_to post.name, post %></h3>
      <p style="color:#808080"><%= link_to post.user, post.user %></p>
      <!--<p><%= post.text %></p>-->
    </li>
  <% end %>
</ul>

<% if current_user && current_user.admin%>
  <% if @user.admin %>
    <span class="label label-success">Admin account</span><br>
  <% end %>
  <%= link_to 'Change blocked status', blockuser_path(id: @user.id), method: :post, class:"btn btn-danger" %>
  <% if @user.blocked == true %>
    <span class="label label-info">Account blocked</span>
  <% end %>
<% end%>
<% if current_user == @user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>