config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :likes, :except => [:new, :edit, :update]
  resources :ratings
  resources :comments
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'blockuser', to: 'users#change_blocked_status'
  root 'posts#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :score, numericality: { greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 100,
                                    only_integer: true }
  validate :user_must_not_have_rated_post, :on => :create

  def user_must_not_have_rated_post
    errors[:you] << 'already rated this post!' if Rating.where(user_id:user_id, post_id:post_id).count > 0
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :set_posts, only: [:new, :edit, :create, :update]
  before_action :ensure_that_signed_in, only: [:create, :update, :destroy]
  before_action :ensure_that_not_blocked, only: [:create, :update, :destroy]
  before_action :ensure_that_there_are_posts, only: [:new, :edit]

  # GET /ratings
  # GET /ratings.json
  def index
    @top_posts = Post.top_last_week
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)
    @rating.user = current_user

    respond_to do |format|
      if current_user && @rating.save
        format.html { redirect_to :back, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.user == current_user && @rating.update(rating_params)
        format.html { redirect_to :back, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy if @rating.user == current_user
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    def set_posts
      @posts = Post.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:score, :post_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %>(0-100)<br>
    <%= f.number_field :score %>
  </div>
  <%= f.select :post_id, options_from_collection_for_select(@posts, :id, :to_s, selected: @rating.post_id) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Top blogs this week</h1>
<p style="color:#808080">Number of posts this week: <%= @top_posts.count %></p>

<ul>
  <% @top_posts.each do |post| %>
    <li>
      <h3><%= link_to post.name, post %></h3>
      <p style="color:#808080">
        By: <%= link_to post.user, post.user %>,
        average of ratings: <%= post.average_rating %>,
        created at: <%= post.created_at.strftime("%A") %>
      </p>
    </li>
  <% end %>
</ul>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @rating.score %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @rating.post_id %>
</p>
<% if current_user && current_user == @rating.user %>
  <%= link_to 'Edit', edit_rating_path(@rating) %> |
<% end %>
<%= link_to 'Back', ratings_path %>