config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :likes, :except => [:new, :edit, :update]
  resources :ratings
  resources :comments
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'blockuser', to: 'users#change_blocked_status'
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include RatingAverage

  belongs_to :user
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, length: { minimum: 4, maximum: 30}
  validates :text, length: { minimum: 10 }

  def most_liked_comment
    comments.sort { |a, b| b.likes_ratio <=> a.likes_ratio }.first
  end

  def self.top_last_week
    Post.where(:created_at => 1.week.ago..Time.now).sort { |a, b| b.average_rating <=> a.average_rating }
  end

  def to_s
    name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, only: [:create, :update, :destroy]
  before_action :ensure_that_not_blocked, only: [:create, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.reverse_order!
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(:post_id => params[:id])
    @comment = Comment.new
    @most_liked_comment = @post.most_liked_comment
    @rating = Rating.where(:post_id => params[:id], :user => current_user).first
    @rating = Rating.new unless @rating
    @like = Like.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if current_user && @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.user == current_user && @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy if (@post.user == current_user || current_user.admin?)
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :text, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def top_this_week
    Post.where(:created_at => 1.week.ago..Time.now).sort { |a, b| b.average_rating <=> a.average_rating }
  end
end

app/views/posts/_comment_form.erb
<strong><%= link_to comment.user, comment.user %>:</strong>
<%= comment.text %>
<% if current_user && current_user == comment.user %>
  <%= link_to 'edit comment', edit_comment_path(comment), class:"btn btn-success" %>
  <%= link_to 'delete comment', comment_path(comment), method: :delete, class:"btn btn-danger" %>
<% elsif current_user %>
  <%= link_to 'like', likes_path(like: true, user_id: current_user.id, comment_id: comment.id), method: :post, class:"btn btn-info" %>
  <%= link_to 'dislike', likes_path(like: false, user_id: current_user.id, comment_id: comment.id), method: :post, class:"btn btn-danger" %>
<% end %>
<% if comment.likes_ratio > 0 %>
  <p style="display:inline;color:#008000">+<%= comment.likes_ratio %></p>
<% elsif comment.likes_ratio < 0 %>
  <p style="display:inline;color:#FF0000"><%= comment.likes_ratio %></p>
<% end %>

app/views/posts/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, cols:100, rows:5 %>
  </div>
  <div class="field">
    <%= f.hidden_field :post_id, :value => @post.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, cols: "100", rows: "50"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_new_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, cols:100, rows:5 %>
  </div>
  <div class="field">
    <%= f.hidden_field :post_id, :value => @post.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_new_rating_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>
    <%= f.hidden_field :post_id, :value => @post.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_rating_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>
    <%= f.hidden_field :post_id, :value => @post.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>BlogPlatform</h1>
<p style="color:#808080">Number of posts: <%= @posts.count %></p>

<ul>
  <% @posts.each do |post| %>
    <li>
      <h3><%= link_to post.name, post %></h3>
      <p style="color:#808080"> 
        By: <%= link_to post.user, post.user %>,
        average of ratings: <%= post.average_rating %>,
      created at: <%= post.created_at.strftime("%A %d %B") %>
      </p>
      <!--<p><%= post.text %></p>-->
    </li>
  <% end %>
</ul>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @post.name %>
</h2>

<p style="color:#808080">
  <strong>Written by:</strong>
  <%= link_to @post.user, @post.user %>
</p>

<p>
  <%= simple_format(@post.text) %>
</p>

<p><strong>Average of <%= pluralize(@post.ratings.count, 'rating') %>:</strong> <%= @post.average_rating %></p>

<%= render 'new_rating_form' %>

<h3>Comments</h3>

<h4>New Comment</h4>

<%= render 'new_comment_form' %>

<p style="display:inline"><strong>Most liked comment:</strong></p>

<% if !@most_liked_comment.nil? %>
  <%= render 'comment_form', comment: @most_liked_comment %>
<% end %>

<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= render 'comment_form', comment: comment%>
    </li>
  <% end %>
</ul>

<% if current_user && current_user == @post.user %>
  <%= link_to 'Edit post', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>