config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :likes, :except => [:new, :edit, :update]
  resources :ratings
  resources :comments
  resources :posts
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'blockuser', to: 'users#change_blocked_status'
  root 'posts#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'BlogPlatform', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Top blogs this week', ratings_path %></li>
<li><%= link_to 'Top comments this week', likes_path %></li>
<% if current_user %>
  <li><%= link_to current_user, current_user %></li>
  <li><%= link_to 'Sign out', session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'Sign in', new_session_path %></li>
  <li><%= link_to 'Sign up', new_user_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blogplatform" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blogplatform" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>